spring.application.name: grew-website-server

spring:
  config:
    activate:
      on-profile: test

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create # todo: Change this line: create -> create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
    show-sql: true
    generate-ddl: true

  datasource:
    url: jdbc:sqlite:./grew_dev.db # Change this line
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin

kakao:
  client-id: kakao_client_id_test
  redirect-uri: http://localhost:8080/oauth/kakao/callback
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me