spring:
  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true # (테스트용) data.sql 사용시에만 적용

  datasource:
    url: ${DB_URL}
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: ${DB_PASSWORD}