spring.application.name: grew-website-server

spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
    show-sql: true
    generate-ddl: true

  datasource:
    url: jdbc:sqlite:./grew_dev.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin