spring.application.name: grew-website-server

spring:
  profiles:
    #    active: dev
    include: secret
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
    show-sql: true
    generate-ddl: true

  datasource:
    url:
    driver-class-name:
    username:
    password:

kakao:
  client-id:
  redirect-uri: http://localhost:8080/oauth/kakao/callback
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me

